# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Tie
version:      0.18
version_from: lib/Date/Tie.pm
installdirs:  site
requires:
    POSIX:                         0
    Tie::Hash:                     0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
